{
  # General parameters
  "mode": "Sample",
  "run_name": "run_sample",
  "batch_size": 16,
  "any_time": 1,

  # Sampling parameters
  "ddim_timesteps": 500,
  "plot": true,
  "sampling_mode": "guided",
  "n_sample": 16,
  "random_noise": true,

  # Data parameters
  "data_dir": "/path/to/your/data/",
  "csv_file": "your_data_labels.csv",
  "v_i": 3,
  "var_indexes": [ "u", "v", "t2m" ],
  "crop": [ 78,206,55,183 ],
  "invert_norm": false,
  "image_size": 128,
  "mean_file": "mean_data.npy",
  "max_file": "max_data.npy",
  "guiding_col": "your_guiding_column",

  # Model parameters
  "scheduler": true,
  "scheduler_epoch": 10,
  "resume": false,
  "epochs": 10,
  "beta_schedule": "linear",
  "model_path": "path/to/model.pt",

  # Tracking parameters
  "wandbproject": "my_project",
  "use_wandb": false,
  "entityWDB": "my_entity"
}
