{
  # General parameters
  "mode": "Sample",
  "run_name": "run_sample",
  "batch_size": 16,
  "any_time": 1,

  # Sampling parameters
  "ddim_timesteps": 500,
  "plot": true,
  "sampling_mode": "conditioned",
  "n_sample": 16,
  "random_noise": true,

  # Data parameters
  "data_dir": "/path/to/your/data/",
  "csv_file": "your_data_labels.csv",
  "output_dir": "/path/to/save/dir/",
  "v_i": 3,
  "var_indexes": [ "u", "v", "t2m" ],
  "crop": [ 0,256,0,256 ],
  "invert_norm": false,
  "mean_file": data_dir/path/to/your_mean_file.npy,
  "max_file": data_dir/path/to/your_max_file.npy,
  "image_size": 256,
  "guiding_col": "your_guiding_column",
  
  # Model parameters
  "scheduler": true,
  "scheduler_epoch": 10,
  "resume": false,
  "epochs": 10,
  "beta_schedule": "linear",
  "model_path": "path/to/model.pt",

  # Tracking parameters
  "wandbproject": "my_project",
  "use_wandb": false,
  "entityWDB": "my_entity"
}
