{
  # General parameters
  "mode": "Train",
  "run_name": "run_train",
  "batch_size": [1],
  "any_time": 25,

  # Sampling parameters
  "ddim_timesteps": 50,
  "plot": true,
  "sampling_mode": "simple",
  "n_sample": 4,
  "random_noise": true,

  # Data parameters
  "data_dir": "../data/small_256/",
  "csv_file": "IS_method_labels.csv",
  "v_i": 3,
  "var_indexes": [ "u", "v", "t2m" ],
  "crop": [ 0,256,0,256 ],
  "invert_norm": false,
  "image_size": 256,
  "mean_file": "mean_with_orog.npy",
  "max_file": "max_with_orog.npy",
  "guiding_col": "ensemble_id",

  # Model parameters
  "scheduler": true,
  "scheduler_epoch": 1,
  "resume": false,
  "epochs": 1,
  "beta_schedule": ["linear", "cosine"],
  "lr": [0.0001, 0.0005, 0.00005],

  # Tracking parameters
  "wandbproject": "your_wandb_project",
  "use_wandb": false,
  "entityWDB": "your_entity"
}
